name: Watcher Py Wheels

on:
  push:
    branches: [ release, next ]
  pull_request:
    branches: [ release, next ]

# macos-13 is an intel runner, which cibw wants for x86 builds... But intel mac is busted.
# https://github.com/e-dant/watcher/actions/runs/9929111640/job/27426247416#step:3:293
# We don't support Windows (but we want to) because meson-python doesn't allow us
# to install shared libraries in wheels for Windows. More info and whatnot here:
# https://github.com/mesonbuild/meson-python/discussions/629
# Other refs, for the action file:
# - https://cibuildwheel.pypa.io/en/stable/setup
# - https://github.com/scikit-image/scikit-image/blob/main/.github/workflows/wheels_recipe.yml
jobs:
  watcher-py-wheels-linux:
    name: (x86_64|aarch64)-unknown-linux-(gnu|musl)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64
      - uses: pypa/cibuildwheel@v2.19.2
        with:
          package-dir: .
          output-dir: wheelhouse
          config-file: pyproject.toml
      - run: python3 tool/shasum.py wheelhouse show
      - run: python3 tool/shasum.py wheelhouse mk
      - uses: actions/upload-artifact@v4
        with:
          name: watcher-py-wheels-linux
          path: wheelhouse/*
  watcher-py-wheels-apple:
    name: aarch64-apple-darwin
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pypa/cibuildwheel@v2.19.2
        env:
          MACOSX_DEPLOYMENT_TARGET: 11
        with:
          package-dir: .
          output-dir: wheelhouse
          config-file: pyproject.toml
      - run: python3 tool/shasum.py wheelhouse show
      - run: python3 tool/shasum.py wheelhouse mk
      - uses: actions/upload-artifact@v4
        with:
          name: watcher-py-wheels-apple
          path: wheelhouse/*
